sudo: required
dist: trusty     # Ubuntu 14.04
services: docker # use Dockerfile
before_install:
- openssl aes-256-cbc -K $encrypted_a63f797455b2_key -iv $encrypted_a63f797455b2_iv -in .dropbox_uploader.enc -out ~\/.dropbox_uploader -d
script:
- wget https://raw.githubusercontent.com/blang/latex-docker/master/latexdockercmd.sh
- chmod +x latexdockercmd.sh
- ./latexdockercmd.sh latexmk -pdf -outdir=./_build
- ./dropbox_uploader.sh upload _build/main.pdf Parichay_NITR-latest.pdf