sudo: required
dist: trusty
services: docker
script:
- chmod +x latexdockercmd.sh
- "./latexdockercmd.sh latexmk -pdf -outdir=./_build"
deploy:
  provider: releases
  api_key: aa0bbda078f021069f5cc28d8effb4ed53beed4a
  file: _build/main.pdf
  skip_cleanup: true
  on:
    repo: baymac/overleaf-resume
    tags: true