language: cpp
compiler:
  - gcc
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-full
script:
  - mkdir -p build
  - xelatex -output-directory=./build main.tex
