sudo: required
dist: trusty
services: docker
script:
- chmod +x latexdockercmd.sh
- "./latexdockercmd.sh latexmk -xelatex sample.tex -outdir=./_build"
deploy:
  provider: releases
  api_key: b4fc13fa0eceac5bcdde581e62b2562f2135c422
  file: _build/sample.pdf
  skip_cleanup: true
  on:
    tags: false