sudo: required
dist: trusty
services: docker
before_install:
- openssl aes-256-cbc -K $encrypted_a63f797455b2_key -iv $encrypted_a63f797455b2_iv
  -in .dropbox_uploader.enc -out ~\/.dropbox_uploader -d
script:
- chmod +x latexdockercmd.sh
- "./latexdockercmd.sh latexmk -xelatex sample.tex -outdir=./_build"
# before_deploy:
# - git config --local user.name "YOUR GIT USER NAME"
# - git config --local user.email "YOUR GIT USER EMAIL"
# - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
# - git tag $TRAVIS_TAG
# deploy:
#   provider: releases
#   api_key: b4fc13fa0eceac5bcdde581e62b2562f2135c422
#   file: _build/sample.pdf
#   skip_cleanup: true

