language: cpp
compiler:
  - gcc
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-fonts-recommended
  - sudo apt-get install texlive-fonts-extra
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install texlive-xetex
script:
  - mkdir -p build
  - xelatex -output-directory=./build main.tex
